export const DataTypeMap = [
    {value: 'username', label: 'Username'},
    {value: 'first-name', label: 'First Name'},
    {value: 'last-name', label: 'Last Name'},
    {value: 'full-name', label: 'Full Name'},
    {value: 'avatar', label: 'Avatar URL'},
    {value: 'birthday', label: 'Birthday date'},
    {value: 'date_soon', label: 'Date soon'},
    {value: 'password', label: 'Password'},
    {value: 'email', label: 'Email'},
    {value: 'phone', label: 'Phone'},
    {value: 'color', label: 'Color'},
    {value: 'gender', label: 'Gender'},
    {value: 'bio', label: 'Biography'},
    {value: 'job_title', label: 'Job Title'},
    {value: 'zodiac', label: 'Zodiac Sign'},
    {value: 'sex', label: 'Binary Sex'},
    {value: 'img_url', label: 'Image'},
    {value: 'img_abstract', label: 'Abstract Image'},
    {value: 'img_animals', label: 'Animals Image'},
    {value: 'img_business', label: 'Business Image'},
    {value: 'img_cats', label: 'Cats Image'},
    {value: 'img_city', label: 'City Image'},
    {value: 'img_fashion', label: 'Fashion Image'},
    {value: 'img_food', label: 'Food Image'},
    {value: 'img_nature', label: 'Nature image'},
    {value: 'img_person', label: 'Person Image'},
    {value: 'img_sports', label: 'Sports Image'},
    {value: 'img_technics', label: 'Technics Image'},
    {value: 'img_transport', label: 'Transport Image'},
    {value: 'text', label: 'Text'},
    {value: 'amount', label: 'Amount'},
    {value: 'credit_card', label: 'Credit Card'},
    {value: 'currency_code', label: 'Currency Code'},
    {value: 'currency_name', label: 'Currency Name'},
    {value: 'currency_symbol', label: 'Currency Symbol'},
    {value: 'account_number', label: 'Account Number'},
    {value: 'account_name', label: 'Account Name'},
    {value: 'commerce_department', label: 'Store Department'},
    {value: 'commerce_isbn', label: 'Product ISBN'},
    {value: 'price', label: 'Price'},
    {value: 'product', label: 'Product Short Name'},
    {value: 'product_description', label: 'Product Description'},
    {value: 'product_descriptive_name', label: 'Product Long Name'},
    {value: 'company_name', label: 'Company Name'},
    {value: 'address_no', label: 'Address Number'},
    {value: 'address_city', label: 'City'},
    {value: 'address_country', label: 'Country'},
    {value: 'address_county', label: 'County'},
    {value: 'address_country_code', label: 'Country Code'},
    {value: 'address_zipcode', label: 'Zipcode'},
    {value: 'address_latitude', label: 'Latitude'},
    {value: 'address_longitude', label: 'Longitude'},
    {value: 'address_state', label: 'State'},
    {value: 'address_street', label: 'Street'},
    {value: 'address_street_address', label: 'Street address'},
    {value: 'address_timezone', label: 'Timezone'},
    {value: 'uuid', label: 'UUID'},
]