import {faker} from "@faker-js/faker";

export const DataTypeMap = new Map([
    ['username', {label: 'Username', generator: () => faker.internet.userName()}],
    ['first-name', {label: 'First Name', generator: () => faker.person.firstName()}],
    ['last-name', {label: 'Last Name', generator: () => faker.person.lastName()}],
    ['full-name', {label: 'Full Name', generator: () => faker.person.fullName}],
    ['avatar', {label: 'Avatar URL', generator: () => faker.image.avatar()}],
    ['birthday', {label: 'Birthday date', generator: () => faker.date.birthdate().toLocaleDateString()}],
    ['date_soon', {label: 'Date soon', generator: () => faker.date.soon().toLocaleDateString()}],
    ['password', {label: 'Password', generator: () => faker.internet.password()}],
    ['email', {label: 'Email', generator: () => faker.internet.email().toLowerCase()}],
    ['phone', {label: 'Phone', generator: () => faker.phone.number()}],
    ['color', {label: 'Color', generator: () => faker.internet.color()}],
    ['gender', {label: 'Gender', generator: () => faker.person.gender()}],
    ['bio', {label: 'Biography', generator: () => faker.person.bio()}],
    ['job_title', {label: 'Job Title', generator: () => faker.person.jobTitle()}],
    ['zodiac', {label: 'Zodiac Sign', generator: () => faker.person.zodiacSign()}],
    ['sex', {label: 'Binary Sex', generator: () => faker.person.sex()}],
    ['img_url', {label: 'Image', generator: () => faker.image.url()}],
    ['img_abstract', {label: 'Abstract Image', generator: () => faker.image.urlLoremFlickr({category: 'abstract'})}],
    ['img_animals', {label: 'Animals Image', generator: () => faker.image.urlLoremFlickr({category: 'animals'})}],
    ['img_business', {label: 'Business Image', generator: () => faker.image.urlLoremFlickr({category: 'business'})}],
    ['img_cats', {label: 'Cats Image', generator: () => faker.image.urlLoremFlickr({category: 'cats'})}],
    ['img_city', {label: 'City Image', generator: () => faker.image.urlLoremFlickr({category: 'city'})}],
    ['img_fashion', {label: 'Fashion Image', generator: () => faker.image.urlLoremFlickr({category: 'fashion'})}],
    ['img_food', {label: 'Food Image', generator: () => faker.image.urlLoremFlickr({category: 'food'})}],
    ['img_nature', {label: 'Nature image', generator: () => faker.image.urlLoremFlickr({category: 'nature'})}],
    ['img_person', {label: 'Person Image', generator: () => faker.image.urlLoremFlickr({category: 'people'})}],
    ['img_sports', {label: 'Sports Image', generator: () => faker.image.urlLoremFlickr({category: 'sports'})}],
    ['img_technics', {label: 'Technics Image', generator: () => faker.image.urlLoremFlickr({category: 'technics'})}],
    ['img_transport', {label: 'Transport Image', generator: () => faker.image.urlLoremFlickr({category: 'transport'})}],
    ['text', {label: 'Text', generator: () => faker.lorem.paragraphs()}],
    ['amount', {label: 'Amount', generator: () => faker.finance.amount()}],
    ['credit_card', {label: 'Credit Card', generator: () => faker.finance.creditCardNumber()}],
    ['currency_code', {label: 'Currency Code', generator: () => faker.finance.currencyCode()}],
    ['currency_name', {label: 'Currency Name', generator: () => faker.finance.currencyName()}],
    ['currency_symbol', {label: 'Currency Symbol', generator: () => faker.finance.currencySymbol()}],
    ['account_number', {label: 'Account Number', generator: () => faker.finance.accountNumber()}],
    ['account_name', {label: 'Account Name', generator: () => faker.finance.accountName()}],
    ['commerce_department', {label: 'Store Department', generator: () => faker.commerce.department()}],
    ['commerce_isbn', {label: 'Product ISBN', generator: () => faker.commerce.isbn()}],
    ['price', {label: 'Price', generator: () => faker.commerce.price()}],
    ['product', {label: 'Product Short Name', generator: () => faker.commerce.product()}],
    ['product_description', {label: 'Product Description', generator: () => faker.commerce.productDescription()}],
    ['product_descriptive_name', {label: 'Product Long Name', generator: () => faker.commerce.productName()}],
    ['company_name', {label: 'Company Name', generator: () => faker.company.name()}],
    ['address_no', {label: 'Address Number', generator: () => faker.location.buildingNumber()}],
    ['address_city', {label: 'City', generator: () => faker.location.city()}],
    ['address_country', {label: 'Country', generator: () => faker.location.country()}],
    ['address_county', {label: 'County', generator: () => faker.location.county()}],
    ['address_country_code', {label: 'Country Code', generator: () => faker.location.countryCode()}],
    ['address_zipcode', {label: 'Zipcode', generator: () => faker.location.zipCode()}],
    ['address_latitude', {label: 'Latitude', generator: () => faker.location.latitude().toString()}],
    ['address_longitude', {label: 'Longitude', generator: () => faker.location.longitude().toString()}],
    ['address_state', {label: 'State', generator: () => faker.location.state()}],
    ['address_street', {label: 'Street', generator: () => faker.location.street()}],
    ['address_street_address', {label: 'Street address', generator: () => faker.location.streetAddress()}],
    ['address_timezone', {label: 'Timezone', generator: () => faker.location.timeZone()}],
    ['uuid', {label: 'UUID', generator: () => faker.string.uuid()}],
])

export const dataOptions: { value: string, label: string }[] = []

for (const item of DataTypeMap) {
    dataOptions.push({value: item[0], label: item[1].label})
}